In [202]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from torch.nn import functional as F


In [203]:
path = '../data/input.txt'
with open(path, 'r', encoding='utf-8') as f:
    text = f.read()

In [204]:
print(text[:100])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [205]:
len(text)

1115394

In [206]:
# Get all chracters of the dataset and create a vocabulary
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [207]:
# Make a character to integer 
stoi = {x:i for i,x in enumerate(chars)}

# And a integer to character
itos = {i:x for x,i in stoi.items()}

In [208]:
itos

{0: '\n',
 1: ' ',
 2: '!',
 3: '$',
 4: '&',
 5: "'",
 6: ',',
 7: '-',
 8: '.',
 9: '3',
 10: ':',
 11: ';',
 12: '?',
 13: 'A',
 14: 'B',
 15: 'C',
 16: 'D',
 17: 'E',
 18: 'F',
 19: 'G',
 20: 'H',
 21: 'I',
 22: 'J',
 23: 'K',
 24: 'L',
 25: 'M',
 26: 'N',
 27: 'O',
 28: 'P',
 29: 'Q',
 30: 'R',
 31: 'S',
 32: 'T',
 33: 'U',
 34: 'V',
 35: 'W',
 36: 'X',
 37: 'Y',
 38: 'Z',
 39: 'a',
 40: 'b',
 41: 'c',
 42: 'd',
 43: 'e',
 44: 'f',
 45: 'g',
 46: 'h',
 47: 'i',
 48: 'j',
 49: 'k',
 50: 'l',
 51: 'm',
 52: 'n',
 53: 'o',
 54: 'p',
 55: 'q',
 56: 'r',
 57: 's',
 58: 't',
 59: 'u',
 60: 'v',
 61: 'w',
 62: 'x',
 63: 'y',
 64: 'z'}

In [209]:
stoi

{'\n': 0,
 ' ': 1,
 '!': 2,
 '$': 3,
 '&': 4,
 "'": 5,
 ',': 6,
 '-': 7,
 '.': 8,
 '3': 9,
 ':': 10,
 ';': 11,
 '?': 12,
 'A': 13,
 'B': 14,
 'C': 15,
 'D': 16,
 'E': 17,
 'F': 18,
 'G': 19,
 'H': 20,
 'I': 21,
 'J': 22,
 'K': 23,
 'L': 24,
 'M': 25,
 'N': 26,
 'O': 27,
 'P': 28,
 'Q': 29,
 'R': 30,
 'S': 31,
 'T': 32,
 'U': 33,
 'V': 34,
 'W': 35,
 'X': 36,
 'Y': 37,
 'Z': 38,
 'a': 39,
 'b': 40,
 'c': 41,
 'd': 42,
 'e': 43,
 'f': 44,
 'g': 45,
 'h': 46,
 'i': 47,
 'j': 48,
 'k': 49,
 'l': 50,
 'm': 51,
 'n': 52,
 'o': 53,
 'p': 54,
 'q': 55,
 'r': 56,
 's': 57,
 't': 58,
 'u': 59,
 'v': 60,
 'w': 61,
 'x': 62,
 'y': 63,
 'z': 64}

In [210]:
itos

{0: '\n',
 1: ' ',
 2: '!',
 3: '$',
 4: '&',
 5: "'",
 6: ',',
 7: '-',
 8: '.',
 9: '3',
 10: ':',
 11: ';',
 12: '?',
 13: 'A',
 14: 'B',
 15: 'C',
 16: 'D',
 17: 'E',
 18: 'F',
 19: 'G',
 20: 'H',
 21: 'I',
 22: 'J',
 23: 'K',
 24: 'L',
 25: 'M',
 26: 'N',
 27: 'O',
 28: 'P',
 29: 'Q',
 30: 'R',
 31: 'S',
 32: 'T',
 33: 'U',
 34: 'V',
 35: 'W',
 36: 'X',
 37: 'Y',
 38: 'Z',
 39: 'a',
 40: 'b',
 41: 'c',
 42: 'd',
 43: 'e',
 44: 'f',
 45: 'g',
 46: 'h',
 47: 'i',
 48: 'j',
 49: 'k',
 50: 'l',
 51: 'm',
 52: 'n',
 53: 'o',
 54: 'p',
 55: 'q',
 56: 'r',
 57: 's',
 58: 't',
 59: 'u',
 60: 'v',
 61: 'w',
 62: 'x',
 63: 'y',
 64: 'z'}

In [211]:
#Encode a string character by character
encode = lambda charstring: [stoi[c] for c in charstring]

#Decode a list of integers to characters
decode = lambda intlist: ''.join([itos[i] for i in intlist])

In [212]:
encode('ostmacka')

[53, 57, 58, 51, 39, 41, 49, 39]

In [213]:
decode(encode('ostmacka'))

'ostmacka'

In [214]:
#Encode our dataset into a torch tensor
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:10])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47])


In [215]:
data.dtype

torch.int64

In [216]:
n = int(0.9*len(data))
traing_data = data[:n]
test_data = data[n:]


In [217]:
#How large our sequence is
block_size = 8
batch_size = 4

In [254]:
def get_batch(X, block_size, batch_size, device='cpu'):
    ix = torch.randint(len(X)-block_size, (batch_size,))
    x = torch.stack([X[i:i+block_size] for i in ix]).to(device)
    y = torch.stack([X[i+1:i+block_size+1] for i in ix]).to(device)
    return x, y

In [219]:
torch.manual_seed(1337)
xb, yb = get_batch(traing_data, block_size, batch_size)

In [220]:
xb

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])

In [221]:
yb

tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])

In [222]:
embedding = nn.Embedding(vocab_size, 15)

In [223]:
embedding(torch.tensor([[1,2],[1,2]])).shape

torch.Size([2, 2, 15])

In [224]:
embedding(xb).shape

torch.Size([4, 8, 15])

In [225]:
xb.shape

torch.Size([4, 8])

In [226]:
B, T, C = embedding(xb).shape
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim = -1)
xbow = wei @ embedding(xb)

In [227]:
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [228]:
wei.shape

torch.Size([8, 8])

In [229]:
xbow.shape

torch.Size([4, 8, 15])

In [230]:
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)

In [231]:
x = torch.randn(B, T, C)

In [232]:

k = key(x)
q = query(x)

In [233]:
wei = q @ k.transpose(-2,-1) # (B, T, head_size) @ (B, head_size, T) --> (B, T, T)
wei.shape


torch.Size([4, 8, 8])

In [234]:
q.shape


torch.Size([4, 8, 16])

In [235]:
k.transpose(-2,-1)

tensor([[[ 8.4444e-01, -1.2236e-01,  3.0955e-01,  5.1334e-02,  1.3492e+00,
          -8.6218e-01,  6.0017e-01, -7.5009e-02],
         [-7.4904e-01,  3.0453e-01,  1.7004e-02, -6.1839e-02, -1.9661e+00,
           8.1425e-01, -1.0588e-01,  3.5661e-01],
         [-1.0378e+00,  1.7232e-01, -3.3471e-01,  3.6014e-01, -9.6117e-02,
           2.7524e-01,  2.2733e-02,  5.8080e-02],
         [ 4.6279e-01, -5.2776e-01,  4.7290e-01, -1.2831e-01,  7.5252e-02,
          -3.9287e-01, -4.1890e-01, -5.1678e-01],
         [ 8.9494e-02,  3.6058e-01, -7.3571e-01, -1.5041e-01,  7.4192e-01,
           9.4202e-01,  1.1735e-01,  1.2284e+00],
         [ 1.1788e+00, -8.8598e-01, -2.2477e-01,  5.6920e-01,  1.0682e+00,
          -3.8678e-01,  5.0850e-01,  9.0173e-01],
         [ 3.9176e-01, -5.7252e-01,  1.4949e+00, -4.5630e-01, -3.2381e-03,
          -9.6991e-01,  2.0642e-01, -3.9829e-01],
         [-5.4469e-02, -3.4297e-01, -8.8394e-02,  1.0209e+00,  7.5130e-01,
          -7.4260e-01,  2.5856e-01, -2.2920e-01],


In [236]:
x = torch.randn(3, 4, 5)
x

tensor([[[-0.0140, -0.2557, -1.1456, -0.0650, -0.8981],
         [ 0.6004, -0.0039,  0.9268, -0.9033, -1.8009],
         [ 0.7865, -1.8513, -0.2894, -0.6531,  0.9476],
         [-0.4904,  0.1995,  1.2089, -0.7427,  0.1015]],

        [[-0.7365, -0.6101, -1.1973, -1.1110, -0.7467],
         [-1.0201,  2.0264,  0.7080, -0.0137,  1.8259],
         [ 1.5226,  0.6569, -1.7636, -0.7221, -0.9141],
         [-0.8221, -1.6358, -1.3221, -1.2953, -0.6008]],

        [[-0.9921, -0.2697,  0.1637,  2.1167, -0.9206],
         [-0.6119, -0.4034,  0.3025,  0.6852, -1.0045],
         [-1.0104, -1.0886, -0.9840,  0.5912, -1.1082],
         [-1.2869, -0.8170,  0.9682,  1.6030, -0.0726]]])

In [237]:
x.transpose(2,1)

tensor([[[-0.0140,  0.6004,  0.7865, -0.4904],
         [-0.2557, -0.0039, -1.8513,  0.1995],
         [-1.1456,  0.9268, -0.2894,  1.2089],
         [-0.0650, -0.9033, -0.6531, -0.7427],
         [-0.8981, -1.8009,  0.9476,  0.1015]],

        [[-0.7365, -1.0201,  1.5226, -0.8221],
         [-0.6101,  2.0264,  0.6569, -1.6358],
         [-1.1973,  0.7080, -1.7636, -1.3221],
         [-1.1110, -0.0137, -0.7221, -1.2953],
         [-0.7467,  1.8259, -0.9141, -0.6008]],

        [[-0.9921, -0.6119, -1.0104, -1.2869],
         [-0.2697, -0.4034, -1.0886, -0.8170],
         [ 0.1637,  0.3025, -0.9840,  0.9682],
         [ 2.1167,  0.6852,  0.5912,  1.6030],
         [-0.9206, -1.0045, -1.1082, -0.0726]]])

In [238]:
x.transpose(1,2).allclose(x.transpose(2,1))

True

In [239]:
# Define a self-attention head
class Head(nn.Module):
    """ 
    One single head of self-attention
    block_size: The largest input length (number of tokens)
    embed_size: The size of the embedding layer: token --> [embed_size]
    head_size: The size of the key, query, value matrices ('Hidden state')
    dropout_rate: The size of the dropout, used at training time
    """
    
    def __init__(self, block_size, embed_size, head_size, dropout_rate=0.2):
        super().__init__()
        self.key = nn.Linear(embed_size, head_size, bias=False)
        self.query = nn.Linear(embed_size, head_size, bias=False)
        self.value = nn.Linear(embed_size, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size))) #Lower triangular matrix used to mask out inputs of earlier times
        self.dropout = nn.Dropout(dropout_rate)

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x) # (B, T, C)
        q = self.query(x) # (B, T, C)
        v = self.value(x) # (B, T, C)
        
        # Compute attention values, that is multiply query and keys
        w = q @ k.transpose(-2,-1) * k.shape[-1]**(-0.5) # (B, T, C) @ (B, C, T) ---> (B, T, T) (Divided by sqrt of C to scale)
        w = w.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T), adding -inf to values outside of the lower triangular part, that is to words that we havn't yet seen
        w = F.softmax(w, dim=-1) # (B, T, T) #Softmax now takes the average of the values leading up to this time T
        w = self.dropout(w) #Add dropout

        #Multiply the output with the value matrix
        out = w @ v # (B, T, T) @ (B, T, C) --> (B, T, C)
        return out    





In [240]:
class MultiHeadAttention(nn.Module):
    def __init__(self, num_heads, block_size, embed_size, head_size, dropout_rate=0.2):
        super().__init__()
        # Simply create num_heads number of heads
        self.heads = nn.ModuleList([Head(block_size, embed_size, head_size, dropout_rate) for _ in range(num_heads)])
        self.FC = nn.Linear(head_size * num_heads, embed_size) #Fully connected layer
        self.dropout = nn.Dropout(dropout_rate) #Dropout for regularization


    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim = -1) #Simply concatinate the multiple heads
        out = self.FC(out)
        out = self.dropout(out)
        return out

In [241]:
class FeedForward(nn.Module):
    """ FC1 --> RELU --> FC2 --> Dropout """
    def __init__(self, embed_size, dropout_rate=0.2):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(embed_size, 4 * embed_size),
            nn.ReLU(),
            nn.Linear(4 * embed_size, embed_size),
            nn.Dropout(dropout_rate)
        )

    def forward(self, x):
        return self.net(x)

In [242]:
class Block(nn.Module):
    """ Transformer block
        num_heads: The number of heads we use
        block_size: The largest input length (number of tokens)
        embed_size: The size of the embedding layer: token --> [embed_size]
        head_size: The size of the key, query, value matrices ('Hidden state')
        dropout_rate: The size of the dropout, used at training time    
    """

    def __init__(self, num_heads,  block_size, embed_size, dropout_rate):
        super().__init__()
        head_size = embed_size // num_heads
        self.sa = MultiHeadAttention(num_heads, block_size, embed_size, head_size, dropout_rate)
        self.ffwd = FeedForward(embed_size, dropout_rate)
        self.layerNorm1 = nn.LayerNorm(embed_size)
        self.layerNorm2 = nn.LayerNorm(embed_size)

    def forward(self, x):
        x = x + self.sa(self.layerNorm1(x))
        x = x + self.ffwd(self.layerNorm2(x))
        return x


In [257]:
class LanguageModel(nn.Module):
    def __init__(self, n_layers, vocab_size, num_heads, block_size, embed_size, dropout_rate):
        super().__init__()
        self.token_embedding = nn.Embedding(vocab_size, embed_size)
        self.position_embedding = nn.Embedding(block_size, embed_size)
        self.blocks = nn.Sequential(*[Block(num_heads,  block_size, embed_size, dropout_rate) for _ in range(n_layers)])
        self.layerNorm = nn.LayerNorm(embed_size)
        self.FC = nn.Linear(embed_size, vocab_size)
        self.block_size = block_size


    def forward(self, idx, targets=None):
        B, T = idx.shape
        device = idx.device

        # Embed idx integers to embedding vectors for each token
        tok_emb = self.token_embedding(idx) # (B, T, C)
        pos_emb = self.position_embedding(torch.arange(T, device=device)) #(T, C)

        x = tok_emb + pos_emb # (B, T, C)
        x = self.blocks(x) # (B, T, C)
        x = self.layerNorm(x) # (B, T, C)

        logits = self.FC(x) # (B, T, vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)

            #loss = nn.CrossEntropyLoss(logits, targets)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context

        with torch.no_grad():
            self.training(False)
            for _ in range(max_new_tokens):

                #Crop if we have too large input
                idx_cond = idx[:, -self.block_size:]

                logits, loss = self(idx_cond)

                #Take last time step only
                logits = logits[:, -1, :] #(B,1,C)

                probs = F.softmax(logits, dim = -1) # (B,C)


                #Sample from the distribution
                idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)

                #Append and concatinate
                idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)

        return idx 


        





In [258]:
n_layers = 4
num_heads = 4
embed_size = 10
dropout_rate = 0.2

model = LanguageModel(n_layers, vocab_size, num_heads, block_size, embed_size, dropout_rate)

In [259]:
print(sum(p.numel() for p in model.parameters())/1e6, 'M parameters')

0.006345 M parameters


In [260]:
max_iters = 5000
eval_interval = 500
learning_rate = 3e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200

In [261]:
model.to(device)

LanguageModel(
  (token_embedding): Embedding(65, 10)
  (position_embedding): Embedding(8, 10)
  (blocks): Sequential(
    (0): Block(
      (sa): MultiHeadAttention(
        (heads): ModuleList(
          (0): Head(
            (key): Linear(in_features=10, out_features=2, bias=False)
            (query): Linear(in_features=10, out_features=2, bias=False)
            (value): Linear(in_features=10, out_features=2, bias=False)
            (dropout): Dropout(p=0.2, inplace=False)
          )
          (1): Head(
            (key): Linear(in_features=10, out_features=2, bias=False)
            (query): Linear(in_features=10, out_features=2, bias=False)
            (value): Linear(in_features=10, out_features=2, bias=False)
            (dropout): Dropout(p=0.2, inplace=False)
          )
          (2): Head(
            (key): Linear(in_features=10, out_features=2, bias=False)
            (query): Linear(in_features=10, out_features=2, bias=False)
            (value): Linear(in_features=1

In [262]:
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

In [ ]:

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = {}
        model.eval()
        for data, name in zip([traing_data, test_data], ['train', 'val']):
            loss_vect = torch.zeros(eval_iters)
            for k in range(eval_iters):
                X, Y = get_batch(data, block_size, batch_size, device)
                logits, loss = model(X, Y)
                loss_vect[k] = loss.item()
            losses[name] = loss_vect.mean()
        model.train()
        
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch(traing_data, block_size, batch_size, device)

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

step 0: train loss 4.3794, val loss 4.3841


In [194]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 64 # how many independent sequences will we process in parallel?
block_size = 256 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 500
learning_rate = 3e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 384
n_head = 6
n_layer = 6
dropout = 0.2
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('../data/input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # input of size (batch, time-step, channels)
        # output of size (batch, time-step, head size)
        B,T,C = x.shape
        k = self.key(x)   # (B,T,hs)
        q = self.query(x) # (B,T,hs)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * k.shape[-1]**-0.5 # (B, T, hs) @ (B, hs, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,hs)
        out = wei @ v # (B, T, T) @ (B, T, hs) -> (B, T, hs)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size * num_heads, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

class GPTLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

        # better init, not covered in the original GPT video, but important, will cover in followup video
        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = GPTLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=500)[0].tolist()))

10.788929 M parameters
step 0: train loss 4.2221, val loss 4.2306
step 500: train loss 1.7593, val loss 1.9105
step 1000: train loss 1.3919, val loss 1.6024
step 1500: train loss 1.2657, val loss 1.5220
step 2000: train loss 1.1902, val loss 1.5081
step 2500: train loss 1.1203, val loss 1.4913
step 3000: train loss 1.0704, val loss 1.4884
step 3500: train loss 1.0149, val loss 1.5022
step 4000: train loss 0.9593, val loss 1.5195
step 4500: train loss 0.9115, val loss 1.5456
step 4999: train loss 0.8581, val loss 1.5775

To enterpent you had now in his shame,
And show himself, to look nose it.

CORIOLANUS:
Would that never dare did raze it?

COMINIUS:
Coriolanus.

BRUTUS:
Have you colld top child this?

COMINIUS:
It doth.
Well, madam, my doe with you.

COMINIUS:
Pray not, here for affliction?
This son myself disgrace these name up?

First Senator:
'Tis censure thou not to him.

COMINIUS:
Our pair o' the malking towards him; so saw'st
thou, in battle. Here's worthless him to accident,
fo